Fix NPE and wrong formatting options:
SimonJPegg/mvn_scalafmt pull request #12
Opened 2017-07-26 17:28 UTC by jbkt

- NullPointerException when no parameters in Maven configuration.
- All files in current directory formatted instead of all files
  in current project (it's a problem on a multi-module projects or when you run maven from another directory).

2017-07-26 19:29 UTC, SimonJPegg requested changes
Looks good, couple of small comments

2017-07-26 19:29 UTC, SimonJPegg commented on pom.xml
> +    <version>0.4_${version.scalafmt}-SNAPSHOT</version>
Could you remove the SNAPSHOT tag?

2017-07-26 19:29 UTC, SimonJPegg commented on src/main/java/org/antipathy/scalafmtmvn/FormatMojo.java
> +    @Parameter(defaultValue = "${project}", required = true, readonly = true)
Could you update the readme to include this new param?

2017-07-26 19:29 UTC, SimonJPegg commented on src/main/scala/org/antipathy/scalafmtmvn/Formatter.scala
> +  def format(configLocation: String, parameters: String, sourceLocations: Array[String]): Unit = {
Could you also update the unit test with the new argument?

2017-07-27 08:29 UTC, jbkt commented on pom.xml
> +    <version>0.4_${version.scalafmt}-SNAPSHOT</version>
Done

2017-07-27 08:30 UTC, jbkt commented on src/main/java/org/antipathy/scalafmtmvn/FormatMojo.java
> +    @Parameter(defaultValue = "${project}", required = true, readonly = true)
Actually this param is not visible by user, it's a Maven property, but I did update the version and fixed some typos in the README.ms.

2017-07-27 08:31 UTC, jbkt commented on src/main/scala/org/antipathy/scalafmtmvn/Formatter.scala
> +  def format(configLocation: String, parameters: String, sourceLocations: Array[String]): Unit = {
Sure, done.

2017-07-27 20:16 UTC, merged

2017-07-27 20:32 UTC, jbkt commented
Thanks for the quick reviews!
When do you think you will be able to release a version?

2017-07-27 20:34 UTC, SimonJPegg commented
Already pushed, should appear on mvn central in the next hour or so.

2017-07-27 20:39 UTC, jbkt commented
Great 👍