Set aggregator in Mojo to execute once in multi-module
SimonJPegg/mvn_scalafmt pull request #15
Opened 2017-10-07 10:41 UTC by maischbe

When executing the plugin in a multi-module project the plugin is called once for each project, leading to problems in configuration and repetitions.

2017-10-14 19:07 UTC, SimonJPegg requested changes
Looks good to me,  could you also bump the version number in the pom (and readme) to 0.6?

2017-11-09 14:47 UTC, jbkt commented
This property is deprecated.
Me working with multi-modules the only problem I have if the configuration file so I put it at the root of my multimodule hierarchy and I reference it like this: 
`<configLocation>${project.parent.basedir}/.scalafmt.conf</configLocation>`

To factorize the configuration use `<pluginManagment>`.

2017-11-09 16:37 UTC, jbkt commented
Actually if you do that you are likely to break existing projects, and to not format anything (source directories are defined at module level).

2017-11-09 16:42 UTC, maischbe commented
@jbkt did you verify your statement? I must admit I'm not fully aware of all implications and I actually solved the problem in a different way in the meantime, but my experience have been that when you run on the root project the plugin would anyway format all scala files in all subfolders without regard for the modules source files...

2017-11-09 16:42 UTC, closed without merging